name: butter
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/dartsidedev/butter
repository: https://github.com/dartsidedev/butter
issue_tracker: https://github.com/dartsidedev/butter/issues
environment:
  sdk: '>=2.10.0 <3.0.0'
#dependencies:
#  path: ^1.7.0
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4

